### PR TITLE
Improving project

### PR DESCRIPTION
**Pull request by dennybiasiolli**
Adding package.json files to simplify contributions

### CODE REVIEW

**Comment by upkarlidder** [comment]
This is great. Thanks @dennybiasiolli 

Fyi @demilolu

**Comment by upkarlidder** [comment]
@dennybiasiolli, with this package.json file, the user will still need a global docsify. Was your intention to not have them do `docsify serve docs` but run the npm start command? I like the idea of package.json as you have it here, but need more clarification on the intent. IMO, if we don't want to pollute their global node install, we should do `npm install` and refer to the node_modules docsify binary in the start script. What do you think?

Thanks again for your help and conrtibution!

**Comment by dennybiasiolli** [comment]
Exactly @upkarlidder , the start script is already using the `docsify` from `node_modules`, but I see that I definitely need to update the readme file for clarifying this, please wait before merging this PR, I'll work on it tomorrow.
Oh, and maybe I can install the docsify dependency as devDependency for coherence

**Comment by upkarlidder** [comment]
Thanks @dennybiasiolli. The start script uses the global `docsify`. You will have to refer to `node_modules/docsify/...` to use the local docsify. Since docsify recommends the global option, how about this route ...
1. install docsify globally
2. `npm install`
3. `npm serve`

Unless you can figure out how to use the local `node_modules` version. I am not sure if you can use docsify that way. Look forward to your comments.

**Comment by dennybiasiolli** [comment]
Well, the npm start script looks like this:
```json
  "scripts": {
    "start": "docsify serve docs"
  },
```

That means that if `docsify` is installed locally (yes it is, because of this lines)
```json
  "dependencies": {
    "docsify-cli": "^4.4.3"
  }
```

The local script inside `node_modules/.bin/docsify` is used instead of the global one, without having to specify the entire path.

Another way to use `docsify` without installing it globally would be to use `npx docsify`.
Same as above, checks are:
- node_modules/.bin/docsify (if present)
- global docsify (if present)
- temporary downloaded docsify if not

Let me know how to act, I'd like to suggest the local installation/usage (or the `npx` one) because users can use `nvm` and don't like to install global dependencies in their environment.
Another reason is that in this way (the local installation one) you can control the exact `docsify` version used, without problems regarding breaking changes, etc...

Let me provide a little fix (docsify from dependencies to devDependencies) and an update to the README file, then you can review that version 😉

**Comment by dennybiasiolli** [comment]
FYI: https://docs.npmjs.com/cli/v7/commands/npm-run-script

> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix. For example, if there is a devDependency on tap in your package, you should write:
>
> `"scripts": {"test": "tap test/*.js"}`
>
> instead of
>
> `"scripts": {"test": "node_modules/.bin/tap test/*.js"}`

**Review by krook — COMMENTED** [review]
Thank you for the contribution! Please make sure the URLs in the package.json file are the canonical ones for the primary repo.

**Comment by dennybiasiolli** [comment]
@krook thanks for spotting that, sorry, didn't see that 😞 
I'm changing that right now

**Comment by upkarlidder** [comment]
> Well, the npm start script looks like this:
> 
> ```json
>   "scripts": {
>     "start": "docsify serve docs"
>   },
> ```
> 
> That means that if `docsify` is installed locally (yes it is, because of this lines)
> 
> ```json
>   "dependencies": {
>     "docsify-cli": "^4.4.3"
>   }
> ```
> 


I had `docsify` instead of `docsify-cli` in my package.json. Of course it does not work 😢 User error for sure. Thanks again for your contribution and a lesson on npm 101 😄

**Review by upkarlidder — APPROVED** [review]

**Comment by krook** [comment]
Thanks again @dennybiasiolli! If you're interested, we also have a parallel repository and minisite for the CFC climate/disaster oriented project where you can propose these improvements as well: https://github.com/Call-for-Code/Hacktoberfest

**Comment by dennybiasiolli** [comment]
Nice! I will look into that repo and try to apply the same improvements there, thanks!

**Pull request merged**
