### PR TITLE
Using prettier

### LINKED ISSUE #9: Add prettier linter for web and markdown files
### Background on the problem the feature will solve/improved user experience
Add `prettier` linter for all files in this repo except node_modules folder. Okay to use the default config for now.

### Describe the solution you'd like
Add GitHub action that checks for linting issues on every branch push and PR created. You can use the following to start with:

```
name: lint

on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
      - run: npm install -g prettier@2.3.0
      - run: prettier --check .
```

### Tasks 
- [ ] add lint.yml to .github/workflows/
- [ ] ensure github action is working by looking at the logs on commit

### Acceptance Criteria 
GitHub action runs no every push and PR created to lint the web and markdown files. The PR is not merged if the linter reports issues with the files.

FYI @demilolu

### PR DESCRIPTION
**Pull request by dennybiasiolli**
Contributes to #9 

## What did you do?

- added prettier as devDependency
- configured `prettier` and `prettier-fix` npm scripts 
- configured `lint.yml` github workflow
- fixed prettier warnings with `npm run prettier-fix`

## Why did you do it?

In order to fix #9

## How have you tested it?

`npm run prettier`

## Were docs updated if needed?

- [ ] No
- [X] Yes
- [ ] N/A

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new console logs
- [X] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Review by upkarlidder — APPROVED** [review]
LGTM. Thanks @dennybiasiolli!

Take a look at the[ other Call for Code for Racial Justice projects](https://call-for-code-for-racial-justice.github.io/Hacktoberfest/#/?id=main) if you are interested.

**Comment by demilolu** [comment]
@dennybiasiolli Thanks for your contribution! would you be available to join us on October 29th for our Demo Day? - https://www.crowdcast.io/e/hacktoberfest-demo-day/register

**Comment by dennybiasiolli** [comment]
@demilolu I'd be happy to participate, thanks, I'll be there!

**Comment by demilolu** [comment]
@dennybiasiolli awesome! Sorry if I missed sending this to you earlier, we'd like to show your PR as part of the event. If you're available we'd like to give you about 2 minutes to talk through the problem/solution you looked at. If you're able to join as a speaker - October 29th at 10 am EST - join us on Slack and DM me @ demi ajayi
[callforcode.org/slack](callforcode.org/slack)

**Comment by dennybiasiolli** [comment]
Yes sure! I'll DM you in a moment, thanks for the invitation!

**Pull request merged**
